### ISSUE TITLE
use releases instead of storing versions in git file tree

### ISSUE THREAD

**Issue by david-shepard** [egaffincahn/finances#2]
use [releases](https://github.com/egaffincahn/finances/releases)  instead of storing versions manually in [git](https://github.com/egaffincahn/finances/tree/master/versions)

**Comment by egaffincahn** [comment]
Suggestion incorporated:

This version updates the transactions from single lines with relevant account changes in the columns into multiple lines for each transaction, bound by a single ID. Each row in the ledger has a budget and account category associated with it, but a single transaction (single ID) can be associated with multiple rows.
